---
- name: Step 000 Post Infrastructure
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tags:
    - step001
    - post_infrastructure
  tasks:
    - debug:
        msg: "Step 000 Post Infrastructure - Dummy action"

    - name: Azure Post Infrastructure
      when: cloud_provider is match("azure")
      block:
      - name: Store SSH Key in shared keyvault
        include_role:
          name: infra-azure-ssh-key
 
      - name: Set FQDN for the bastion VM
        when: item.name is match('bastion')
        set_fact:
          rhel_remote_host: "{{item.fqdns|d(item.publicIps)|d('')}}"
        with_items: "{{vm_list}}"
 
      - name: Print Host Information
        agnosticd_user_info:
          msg: "{{ item }}"
        loop:
        - "Remote User: {{ remote_user }}"
        - "RHEL Bastion Host: {{ rhel_remote_host }}"
        when: ocp4_cluster_show_access_user_info | bool
